In [1]:
import os
os.chdir('./back-end/')
!pwd

FileNotFoundError: [Errno 2] No such file or directory: './back-end/'

In [10]:
import gpt
from importlib import reload
reload(gpt)
from gpt import *

Num GPUs Available:  0
Is GPU available:  False
GPU Device Name:  


All PyTorch model weights were used when initializing TFGPT2LMHeadModel.

All the weights of TFGPT2LMHeadModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


loaded <transformers.models.gpt2.modeling_tf_gpt2.TFGPT2LMHeadModel object at 0x31aea7760>


In [11]:
if __name__ == "__main__":
    # Example usage
    # for token in pluck_probs("This is a test.", top_k=3):
    #     print(token)
    #     print(json.dumps(token))

    input = "I like mountains "
    output = forward_search(input, top_k=10, depth=18, logits_processor=logits_processor)
    print_output(input, output)

forward |I like mountains| k 10 depth 18 beams 9 beam groups 3 ends space True
{'input_ids': <tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[   40,   588, 12269]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 1, 1]], dtype=int32)>, 'offset_mapping': <tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 1,  6],
        [ 6, 16]]], dtype=int32)>}
ends with space True input_len 3 max_length 21
Shape of beam_token_scores: [TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257]), TensorShape([9, 50257])]
<class 'list'>
I like mountains and mountains, but I do